# Generated by Django 5.0.1 on 2024-01-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workerregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=20)),
                ('worker_password', models.CharField(max_length=20)),
                ('worker_email', models.EmailField(max_length=254)),
                ('worker_salary', models.IntegerField()),
                ('worker_proof', models.FileField(upload_to='UserDocs/')),
                ('worker_photo', models.FileField(upload_to='UserDocs/')),
                ('worker_status', models.IntegerField(default=0)),
            ],
        ),
    ]
