# Generated by Django 5.0.1 on 2024-01-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panchayath', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_workerregistration',
        ),
    ]
