# Generated by Django 5.0.1 on 2024-01-06 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_waste'),
        ('Panchayath', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_workerregistration',
            name='ward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward'),
        ),
    ]
