# Generated by Django 5.0.1 on 2024-01-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panchayath', '0008_tbl_workerregistration_ward_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateField()),
                ('salary_amount', models.IntegerField(max_length=20)),
                ('salary_status', models.IntegerField(default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Panchayath.tbl_workerregistration')),
            ],
        ),
    ]
