# Generated by Django 5.0 on 2023-12-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_panchayath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayath_name', models.CharField(max_length=20)),
                ('panchayath_contact', models.IntegerField()),
                ('panchayath_email', models.EmailField(max_length=254)),
                ('panchayath_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_email',
            field=models.EmailField(max_length=254),
        ),
    ]
