# Generated by Django 5.0 on 2023-12-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
        migrations.RemoveField(
            model_name='tbl_ward',
            name='panchayath',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
        migrations.DeleteModel(
            name='tbl_panchayath',
        ),
        migrations.DeleteModel(
            name='tbl_ward',
        ),
    ]
