# Generated by Django 5.0.1 on 2024-01-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newuser',
        ),
    ]
