# Generated by Django 5.0.1 on 2024-01-05 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_waste'),
        ('Guest', '0002_delete_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_contact', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_proof', models.FileField(upload_to='UserDocs/')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=20)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
