# Generated by Django 5.0.1 on 2024-01-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
