# Generated by Django 5.0.1 on 2024-01-22 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
