# Generated by Django 5.0.1 on 2024-01-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_remove_tbl_complaint_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
