# Generated by Django 5.0.1 on 2024-01-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
